baseURL = 'https://int8.tech/'
languageCode = 'en-us'
title = 'int8 blog'
theme = 'int8'
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.128.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rtt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = false

[params]
  author = "Clement POIRET"
  github = "https://github.com/clementpoiret"
  og_image = "/images/og.png"
  sitename = "int8 blog"
  twitter = "@clement_poiret1"
  enableRobotsTXT = true

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = ".."
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
